def get_content(comp):
    content = ['Maciej Jaroszewski','511 826 318', 'mjaroszewski1979@gmail.com', 'tdy', 'cmp', 'Dear Sirs,', 'This letter is to express my interest in the Software Developer position. I am excited about the opportunity to join your team and contribute my experiences to the company. In my previous roles, I learned how to handle multiple tasks efficiently, work well under pressure, and communicate effectively with both customers and colleagues. I also gained valuable problem-solving skills and the ability to learn new systems and technologies quickly. I have always been interested in computers and have taught myself the basics of programming. I am now eager to take my competence to the next level by learning from experienced professionals and working on real-world projects.',
    'During my time as a Restaurant Manager i have acquired the ability to handle multiple tasks and prioritize work effectively. On many occasions it was necessary to deal with customer complaints and requests, which can be useful experience for working with clients in a software development role. My prime concern was ensuring that the restaurant ran smoothly and that all issues were addressed in a timely manner. Thanks to good organizational skills as well as a strong team work ethic, we were able to finish every project within the deadline.', 
    'In my current role I work in a group that is comprised of many different disciplines, therefore I need to be cognizant of their respective expertise and know when to yield to their discretion. We are using technical specifications on a daily basis which outlines the requirements and features that a product has to have in order to work as intended. Furthermore, my company rely on SAP as their core ERP platform, which has exposed me to new fields and strengthened my database management skills. As someone with assembly technical experience i have good understanding how different components fit together which can be valuable in working with complex systems.',
    f"I would be grateful for the opportunity to discuss my qualifications further and learn more about the opportunities at {comp}. As a Software Developer, my goal is to continually increase my programming skills in order to present better solutions to my employers and their clients. I am particularly interested in working at {comp} because of your reputation for developing innovative products and technologies. I believe that my experience make me a strong fit for your team, and I am eager to be a part of your company's growth and success. Thank you for taking the time to review my cover letter and attached resume.",
    'Kind Regards,', 'Maciej Jaroszewski']
    return content

spaces = [0,0,5,5,10,7,5,5,5,7,10,0]

